/**
 * Shared B1「导入/版本」executing check (D4-1 wave, issue #8 charter §6 B1).
 *
 * Runs the REAL import pipeline (MaterialImportService + MaterialRepository +
 * the wired d4-md-v1 / d4-pdf-v1 parsers) in a throwaway SQLite database
 * against whatever b1-import registries exist at runtime:
 *
 *  - md-registry.json AND pdf-registry.json are enumerated generically (either
 *    may be absent while its parallel wave is in flight);
 *  - every registered READY fixture must round-trip to its frozen
 *    *.expected.json truth byte-exactly (canonicalText + full block map,
 *    incl. pdf page numbers), and re-importing the same bytes must REUSE the
 *    version (zero new rows — 重复导入不重复版本);
 *  - every registered NEGATIVE must be honestly rejected: either at the
 *    import gate (honest error type, zero persistence — e.g. an empty file)
 *    or as a terminal failed version whose parseError carries the frozen
 *    reason code; a ready outcome is a FAIL (不得伪装成功空文档);
 *  - registered version pairs, when their source files are locatable, must
 *    append a second version with the old version still readable and both
 *    truths intact (改版保留旧来源); pairs whose source files cannot be
 *    located are reported as not executed (registration-only), not silently
 *    dropped and not a failure;
 *  - when tests/fixtures/d4/manifest.json registers generatedOversize probes
 *    (3 charter §5 negatives: >20 MiB / >200 pages / >1M UTF-16 units), the
 *    three probes are generated deterministically HERE and executed: each
 *    must be rejected before exhausting resources with the matching reason
 *    (material-too-large / pages-exceeded / text-units-exceeded). If the
 *    manifest is absent the probes are reported as not registered — not a
 *    failure (the parallel wave owns that file).
 *
 * Consumers: scripts/verify-d4.js (check `b1-import-versions`). The frozen
 * fixture tree stays read-only — nothing under tests/fixtures/d4 is written
 * or regenerated by this check.
 */

import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { MaterialRepository, TreeRepository } from "@treeai/persistence";
import type { MaterialId, MaterialVersion, MaterialVersionId, TreeId } from "@treeai/contracts";
import {
  MaterialImportService,
  MaterialNotReadyError,
  MaterialTooLargeError,
  MaterialUnsupportedError,
} from "../../../apps/studio/src/materials/import-service.ts";

export interface B1ImportCheckOutcome {
  readonly status: "PASS" | "FAIL" | "NOT_RUN";
  readonly exitCode: number | null;
  /** One-line summary for the check matrix. */
  readonly detail: string;
  /** Per-fixture execution lines (evidence log). */
  readonly lines: readonly string[];
  readonly problems: readonly string[];
}

/* ------------------------------------------------------------------ */
/* Frozen fixture shapes (mirrors d4-probes.ts field vocabulary)         */
/* ------------------------------------------------------------------ */

interface RegistryFixtureEntry {
  readonly [key: string]: unknown;
}
interface Registry {
  readonly kind: string;
  readonly fixtures: readonly RegistryFixtureEntry[];
  readonly negativeFixtures: readonly RegistryFixtureEntry[];
  readonly versionPairs: readonly Record<string, unknown>[];
}
interface ExpectedTruth {
  readonly fixtureId: string;
  readonly normalizer: string;
  readonly canonicalText: string;
  readonly blocks: readonly {
    blockId: string;
    kind: string;
    start: number;
    end: number;
    page?: number;
    text: string;
  }[];
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
}
function asString(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}
function asArray(value: unknown): unknown[] | null {
  return Array.isArray(value) ? value : null;
}

function readJson(path: string, problems: string[], what: string): Record<string, unknown> | null {
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8")) as unknown;
    const record = asRecord(parsed);
    if (record === null) {
      problems.push(`${what}: not a JSON object at ${path}`);
      return null;
    }
    return record;
  } catch (error) {
    problems.push(`${what}: unreadable/invalid JSON at ${path} (${error instanceof Error ? error.message : String(error)})`);
    return null;
  }
}

function loadExpected(path: string, problems: string[], fixtureId: string): ExpectedTruth | null {
  const raw = readJson(path, problems, `b1 expected ${fixtureId}`);
  if (raw === null) return null;
  const fixtureIdF = asString(raw["fixtureId"]);
  const normalizer = asString(raw["normalizer"]);
  const canonicalText = asString(raw["canonicalText"]);
  const blocksRaw = asArray(raw["blocks"]);
  if (canonicalText === null || blocksRaw === null) {
    problems.push(`b1 expected ${fixtureId}: missing canonicalText/blocks`);
    return null;
  }
  const blocks: { blockId: string; kind: string; start: number; end: number; page?: number; text: string }[] = [];
  for (const b of blocksRaw) {
    const r = asRecord(b);
    if (r === null) {
      problems.push(`b1 expected ${fixtureId}: non-object block entry`);
      return null;
    }
    const blockId = asString(r["blockId"]);
    const kind = asString(r["kind"]);
    const text = asString(r["text"]);
    const start = r["start"];
    const end = r["end"];
    if (blockId === null || kind === null || text === null || typeof start !== "number" || typeof end !== "number") {
      problems.push(`b1 expected ${fixtureId}: malformed block entry`);
      return null;
    }
    const page = r["page"];
    blocks.push({ blockId, kind, start, end, text, ...(typeof page === "number" ? { page } : {}) });
  }
  return {
    fixtureId: fixtureIdF ?? fixtureId,
    normalizer: normalizer ?? "?",
    canonicalText,
    blocks,
  };
}

/* ------------------------------------------------------------------ */
/* Deterministic oversize probe generators (charter §5)                  */
/* ------------------------------------------------------------------ */

/** latin1 字符串 → 字节（探针装配用；内容为 ASCII / 纯中文，均可无损往返）。 */
function latin1BytesOf(text: string): Uint8Array {
  const out = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i += 1) out[i] = text.charCodeAt(i) & 0xff;
  return out;
}
function utf8BytesOf(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

/** >20 MiB 的确定性 markdown 探针（文件字节上限；读体/解析前拒绝）。 */
function buildOversizeFileBytes(): Uint8Array {
  const line = "oversize probe: charter D4 section 5 single-file 20 MiB limit (deterministic verify-time generation)\n";
  const target = 20 * 1024 * 1024 + 1;
  const repeats = Math.ceil(target / line.length);
  return utf8BytesOf(line.repeat(repeats).slice(0, target));
}

/** >1,000,000 UTF-16 单元、≤20 MiB 的确定性 markdown 探针（解析后、落库前拒绝）。 */
function buildOversizeTextUnitsBytes(): Uint8Array {
  /* 每个「字」= 1 UTF-16 单元 / 3 UTF-8 字节：1,000,001 单元 ≈ 3 MB。 */
  return utf8BytesOf("字".repeat(1_000_001));
}

/** >200 页的确定性单字体 PDF 探针（页树装载后、内容解释前拒绝）。 */
function buildOversizePagesPdf(pageCount: number): Uint8Array {
  const content = "BT /F1 12 Tf 72 700 Td (oversize pages probe) Tj ET";
  const bodies: string[] = [];
  bodies.push("<< /Type /Catalog /Pages 2 0 R >>"); // 1
  bodies.push(""); // 2: Pages（最后回填）
  bodies.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"); // 3
  const pageRefs: string[] = [];
  for (let i = 0; i < pageCount; i += 1) {
    const contentNum = bodies.push(`<< /Length ${String(content.length)} >>\nstream\n${content}\nendstream`);
    const pageNum = bodies.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] ` +
        `/Resources << /Font << /F1 3 0 R >> >> /Contents ${String(contentNum)} 0 R >>`,
    );
    pageRefs.push(`${String(pageNum)} 0 R`);
  }
  bodies[1] = `<< /Type /Pages /Kids [${pageRefs.join(" ")}] /Count ${String(pageRefs.length)} >>`;
  const parts: string[] = ["%PDF-1.5\n%\xE2\xE3\xCF\xD3\n"];
  const offsets: number[] = [];
  let pos = parts[0]!.length;
  bodies.forEach((body, i) => {
    offsets.push(pos);
    const chunk = `${String(i + 1)} 0 obj\n${body}\nendobj\n`;
    parts.push(chunk);
    pos += chunk.length;
  });
  const xrefStart = pos;
  let xref = `xref\n0 ${String(bodies.length + 1)}\n0000000000 65535 f \n`;
  for (const off of offsets) xref += `${String(off).padStart(10, "0")} 00000 n \n`;
  parts.push(xref);
  parts.push(`trailer\n<< /Size ${String(bodies.length + 1)} /Root 1 0 R >>\nstartxref\n${String(xrefStart)}\n%%EOF\n`);
  return latin1BytesOf(parts.join(""));
}

/* ------------------------------------------------------------------ */
/* The check                                                            */
/* ------------------------------------------------------------------ */

interface Harness {
  readonly service: MaterialImportService;
  readonly treeRepository: TreeRepository;
  readonly materialRepository: MaterialRepository;
  readonly treeId: TreeId;
  readonly dir: string;
  dispose(): void;
}

function openHarness(): Harness {
  const dir = mkdtempSync(join(tmpdir(), "treeai-d4-b1-"));
  const dbPath = join(dir, "treeai.db");
  const treeRepository = TreeRepository.open({ path: dbPath });
  const materialRepository = MaterialRepository.open({ path: dbPath });
  const service = new MaterialImportService({ repository: materialRepository });
  const forest = treeRepository.createForest();
  const tree = treeRepository.createTree(forest.id);
  return {
    service,
    treeRepository,
    materialRepository,
    treeId: tree.id,
    dir,
    dispose(): void {
      materialRepository.close();
      treeRepository.close();
      rmSync(dir, { recursive: true, force: true });
    },
  };
}

const TERMINAL_STATUSES: ReadonlySet<string> = new Set(["ready", "failed", "canceled", "unsupported", "rejected"]);

async function untilTerminal(
  harness: Harness,
  materialId: MaterialId,
  timeoutMs: number,
  problems: string[],
): Promise<MaterialVersion | null> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const detail = harness.service.getMaterialDetail(harness.treeId, materialId);
    const version = detail.versions[detail.versions.length - 1] ?? null;
    if (version !== null && TERMINAL_STATUSES.has(version.parseStatus)) {
      return version;
    }
    if (Date.now() > deadline) {
      problems.push(`timed out waiting for a terminal parse status (material ${materialId})`);
      return null;
    }
    await new Promise((resolve) => setTimeout(resolve, 5));
  }
}

/** 分页读尽版本块图（真实读取面，非内部直查）。 */
function readAllBlocks(
  harness: Harness,
  materialId: MaterialId,
  versionId: MaterialVersionId,
): { blockId: string; kind: string; start: number; end: number; page?: number; text: string }[] {
  const out: { blockId: string; kind: string; start: number; end: number; page?: number; text: string }[] = [];
  let afterBlock: string | null = null;
  for (;;) {
    const page = harness.service.readVersionBlocks(
      harness.treeId,
      materialId,
      versionId,
      afterBlock === null ? {} : { afterBlock },
    );
    for (const entry of page.blocks) {
      out.push({
        blockId: entry.block.blockId,
        kind: entry.block.kind,
        start: entry.block.start,
        end: entry.block.end,
        ...(entry.block.page !== undefined ? { page: entry.block.page } : {}),
        text: entry.text,
      });
    }
    if (page.nextAfterBlock === null) return out;
    afterBlock = page.nextAfterBlock;
  }
}

function basename(path: string): string {
  return path.split("/").pop() ?? path;
}

async function runB1ImportCheck(d4Root: string): Promise<B1ImportCheckOutcome> {
  const problems: string[] = [];
  const lines: string[] = [];
  const b1Root = join(d4Root, "b1-import");
  if (!existsSync(b1Root)) {
    return {
      status: "NOT_RUN",
      exitCode: null,
      detail: "tests/fixtures/d4/b1-import not present in this tree",
      lines,
      problems,
    };
  }

  /* ---- enumerate registries generically (either wave may be absent) ---- */
  const registries: { name: string; registry: Registry }[] = [];
  for (const name of ["md-registry.json", "pdf-registry.json"]) {
    const path = join(b1Root, name);
    if (!existsSync(path)) continue;
    const raw = readJson(path, problems, `b1 ${name}`);
    if (raw === null) continue;
    const kind = asString(raw["kind"]) ?? "?";
    const fixtures = (asArray(raw["fixtures"]) ?? []).filter((f): f is RegistryFixtureEntry => asRecord(f) !== null);
    const negatives = (asArray(raw["negativeFixtures"]) ?? []).filter((f): f is RegistryFixtureEntry => asRecord(f) !== null);
    const pairs = (asArray(raw["versionPairs"]) ?? []).filter((p): p is Record<string, unknown> => asRecord(p) !== null);
    registries.push({ name, registry: { kind, fixtures, negativeFixtures: negatives, versionPairs: pairs } });
  }
  if (registries.length === 0) {
    return {
      status: "NOT_RUN",
      exitCode: null,
      detail: "no b1-import registries present (md-registry.json / pdf-registry.json both absent)",
      lines,
      problems,
    };
  }

  const harness = openHarness();
  let readyOk = 0;
  let readyTotal = 0;
  let negativesOk = 0;
  let negativesTotal = 0;
  let reuseOk = 0;
  let pairsExecuted = 0;
  let pairsRegistered = 0;
  const negativeReasons = new Map<string, number>();
  try {
    /* ---- ready fixtures: byte-exact round-trip + same-bytes reuse ---- */
    for (const { name, registry } of registries) {
      const expectedVersion = registry.kind === "markdown" ? "d4-md-v1" : "d4-pdf-v1";
      for (const fixture of registry.fixtures) {
        readyTotal += 1;
        const fixtureId = asString(fixture["fixtureId"]) ?? "?";
        const file = asString(fixture["file"]);
        const expectedPath = asString(fixture["expected"]);
        const outcome = asString(fixture["outcome"]) ?? "?";
        if (file === null || expectedPath === null) {
          problems.push(`${name}: ready fixture ${fixtureId} missing file/expected`);
          continue;
        }
        if (outcome !== "ready") {
          problems.push(`${name}: fixture ${fixtureId} has non-ready outcome '${outcome}' (only 'ready' belongs in fixtures)`);
          continue;
        }
        const bytesPath = join(b1Root, file);
        if (!existsSync(bytesPath)) {
          problems.push(`${name}: fixture file missing on disk: ${file}`);
          continue;
        }
        const expected = loadExpected(join(b1Root, expectedPath), problems, fixtureId);
        if (expected === null) continue;
        if (expected.normalizer !== expectedVersion) {
          problems.push(`${name}: ${fixtureId} expected normalizer ${expected.normalizer} != ${expectedVersion}`);
          continue;
        }
        const bytes = new Uint8Array(readFileSync(bytesPath));
        try {
          const imported = await harness.service.importMaterial(harness.treeId, { filename: basename(file), bytes });
          const version = await untilTerminal(harness, imported.material.id, 60_000, problems);
          if (version === null) continue;
          if (version.parseStatus !== "ready") {
            problems.push(`${fixtureId}: expected ready, got '${version.parseStatus}' (${version.parseError ?? ""})`);
            lines.push(`${fixtureId}: FAIL ${version.parseStatus} ${version.parseError ?? ""}`);
            continue;
          }
          if (version.parserKind !== registry.kind || version.parserVersion !== expectedVersion) {
            problems.push(
              `${fixtureId}: parsed as ${version.parserKind}/${version.parserVersion}, expected ${registry.kind}/${expectedVersion}`,
            );
            continue;
          }
          /* 全量分页读取后与冻结真值逐字节比对（块图 + 文本）。 */
          const read = readAllBlocks(harness, imported.material.id, imported.version.id);
          const gotText = read.map((entry) => entry.text).join("");
          if (gotText !== expected.canonicalText) {
            problems.push(
              `${fixtureId}: canonical text diverges from the frozen truth (${String(gotText.length)} vs ${String(expected.canonicalText.length)} units)`,
            );
            continue;
          }
          const expectedBlocks = expected.blocks.map((b) => ({
            blockId: b.blockId,
            kind: b.kind,
            start: b.start,
            end: b.end,
            ...(b.page !== undefined ? { page: b.page } : {}),
          }));
          const gotBlocks = read.map((entry) => ({
            blockId: entry.blockId,
            kind: entry.kind,
            start: entry.start,
            end: entry.end,
            ...(entry.page !== undefined ? { page: entry.page } : {}),
          }));
          if (JSON.stringify(gotBlocks) !== JSON.stringify(expectedBlocks)) {
            problems.push(`${fixtureId}: block map diverges from the frozen truth`);
            continue;
          }
          if (version.textUnits !== expected.canonicalText.length) {
            problems.push(`${fixtureId}: textUnits ${String(version.textUnits)} != ${String(expected.canonicalText.length)}`);
            continue;
          }
          /* 同字节重导（不同文件名）：复用同一版本，零新行。 */
          const reimport = await harness.service.importMaterial(harness.treeId, {
            filename: `reimport-of-${basename(file)}`,
            bytes,
          });
          if (reimport.created !== false || reimport.version.id !== imported.version.id) {
            problems.push(`${fixtureId}: same-bytes re-import did not reuse the version (created=${String(reimport.created)})`);
            continue;
          }
          reuseOk += 1;
          readyOk += 1;
          lines.push(
            `${fixtureId}: ready ok — ${String(read.length)} block(s), ${String(expected.canonicalText.length)} units, ` +
              `re-import reuses (${registry.kind})`,
          );
        } catch (error) {
          problems.push(`${fixtureId}: import crashed: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }

    /* ---- negatives: honest rejection with the frozen reason ---- */
    for (const { name, registry } of registries) {
      for (const negative of registry.negativeFixtures) {
        negativesTotal += 1;
        const fixtureId = asString(negative["fixtureId"]) ?? "?";
        const file = asString(negative["file"]);
        const reason = asString(negative["reason"]) ?? "?";
        if (file === null) {
          problems.push(`${name}: negative ${fixtureId} missing file`);
          continue;
        }
        const bytesPath = join(b1Root, file);
        if (!existsSync(bytesPath)) {
          problems.push(`${name}: negative file missing on disk: ${file}`);
          continue;
        }
        const bytes = new Uint8Array(readFileSync(bytesPath));
        try {
          const imported = await harness.service.importMaterial(harness.treeId, { filename: basename(file), bytes });
          const version = await untilTerminal(harness, imported.material.id, 60_000, problems);
          if (version === null) continue;
          if (version.parseStatus === "ready") {
            problems.push(`${fixtureId}: negative produced a READY version (must reject, never fake an empty success)`);
            continue;
          }
          if (version.parseStatus !== "failed") {
            problems.push(`${fixtureId}: negative ended '${version.parseStatus}' (expected failed with a reason)`);
            continue;
          }
          const parseError = version.parseError ?? "";
          if (!parseError.startsWith(`${reason}:`)) {
            problems.push(`${fixtureId}: parseError '${parseError}' does not carry the frozen reason '${reason}'`);
            continue;
          }
          if (version.textUnits !== 0) {
            problems.push(`${fixtureId}: rejected document stored ${String(version.textUnits)} text units`);
            continue;
          }
          let notReadyRefused = false;
          try {
            harness.service.readVersionBlocks(harness.treeId, imported.material.id, imported.version.id, {});
          } catch (error) {
            notReadyRefused = error instanceof MaterialNotReadyError;
          }
          if (!notReadyRefused) {
            problems.push(`${fixtureId}: reads of the rejected version are not refused as material-not-ready`);
            continue;
          }
          negativesOk += 1;
          negativeReasons.set(reason, (negativeReasons.get(reason) ?? 0) + 1);
          lines.push(`${fixtureId}: rejected ok — ${reason}`);
        } catch (error) {
          /* 导入门拒绝（如空文件）也算诚实拒绝——错误类型如实且零持久化。 */
          if (error instanceof MaterialUnsupportedError || error instanceof MaterialTooLargeError) {
            negativesOk += 1;
            negativeReasons.set(reason, (negativeReasons.get(reason) ?? 0) + 1);
            lines.push(`${fixtureId}: rejected ok — ${reason} (at the import gate)`);
            continue;
          }
          if (reason === "empty" && error instanceof Error && error.name === "InvalidArgumentError") {
            negativesOk += 1;
            negativeReasons.set(reason, (negativeReasons.get(reason) ?? 0) + 1);
            lines.push(`${fixtureId}: rejected ok — empty (rejected before parsing, zero persistence)`);
            continue;
          }
          problems.push(`${fixtureId}: import crashed: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }

    /* ---- version pairs (best effort; registration-only pairs are noted) ---- */
    for (const { registry } of registries) {
      for (const pair of registry.versionPairs) {
        pairsRegistered += 1;
        const materialKey = asString(pair["materialKey"]) ?? "?";
        /* 源文件发现：登记项的字符串（或字符串数组）值里存在且非真值 JSON 的材料文件。 */
        const candidates: { field: string; value: string }[] = [];
        for (const [field, value] of Object.entries(pair)) {
          if (typeof value === "string" && /\.(md|markdown|pdf)$/.test(value) && existsSync(join(b1Root, value))) {
            candidates.push({ field, value });
          } else if (Array.isArray(value)) {
            value.forEach((item, index) => {
              if (typeof item === "string" && /\.(md|markdown|pdf)$/.test(item) && existsSync(join(b1Root, item))) {
                candidates.push({ field: `${field}[${String(index)}]`, value: item });
              }
            });
          }
        }
        if (candidates.length < 2) {
          lines.push(`version pair ${materialKey}: registered but source files not located — chain not executed (no fail)`);
          continue;
        }
        candidates.sort((a, b) => (a.field < b.field ? -1 : 1));
        const v1 = candidates[0]!;
        const v2 = candidates[1]!;
        const v1Expected = asString(pair["v1Expected"]);
        const v2Expected = asString(pair["v2Expected"]);
        try {
          const first = await harness.service.importMaterial(harness.treeId, {
            filename: basename(v1.value),
            bytes: new Uint8Array(readFileSync(join(b1Root, v1.value))),
          });
          const firstVersion = await untilTerminal(harness, first.material.id, 60_000, problems);
          if (firstVersion === null || firstVersion.parseStatus !== "ready") {
            problems.push(`version pair ${materialKey}: v1 did not reach ready`);
            continue;
          }
          const second = await harness.service.addMaterialVersion(harness.treeId, first.material.id, {
            filename: basename(v2.value),
            bytes: new Uint8Array(readFileSync(join(b1Root, v2.value))),
          });
          if (second.created !== true || second.version.id === first.version.id) {
            problems.push(`version pair ${materialKey}: v2 bytes did not append a new version`);
            continue;
          }
          const secondVersion = await untilTerminal(harness, second.material.id, 60_000, problems);
          if (secondVersion === null || secondVersion.parseStatus !== "ready") {
            problems.push(`version pair ${materialKey}: v2 did not reach ready`);
            continue;
          }
          const versions = harness.service.getMaterialDetail(harness.treeId, first.material.id).versions;
          if (versions.length !== 2) {
            problems.push(`version pair ${materialKey}: version chain has ${String(versions.length)} rows (expected 2)`);
            continue;
          }
          /* 改版保留旧来源：v1 在 v2 落地后仍可读且与真值一致。 */
          if (v1Expected !== null && v2Expected !== null) {
            const e1 = loadExpected(join(b1Root, v1Expected), problems, `${materialKey}-v1`);
            const e2 = loadExpected(join(b1Root, v2Expected), problems, `${materialKey}-v2`);
            if (e1 !== null && e2 !== null) {
              const r1 = readAllBlocks(harness, first.material.id, first.version.id).map((entry) => entry.text).join("");
              const r2 = readAllBlocks(harness, first.material.id, second.version.id).map((entry) => entry.text).join("");
              if (r1 !== e1.canonicalText) {
                problems.push(`version pair ${materialKey}: v1 truth changed after v2 landed (old sources must stay readable)`);
                continue;
              }
              if (r2 !== e2.canonicalText) {
                problems.push(`version pair ${materialKey}: v2 does not match its frozen truth`);
                continue;
              }
            }
          }
          pairsExecuted += 1;
          lines.push(`version pair ${materialKey}: v1→v2 appended; both truths intact; old version readable`);
        } catch (error) {
          problems.push(`version pair ${materialKey}: crashed: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }

    /* ---- generated oversize probes (charter §5; manifest-gated) ---- */
    let oversizeNote = "not registered (manifest.json absent) — not executed";
    const manifestPath = join(d4Root, "manifest.json");
    if (existsSync(manifestPath)) {
      const manifest = readJson(manifestPath, problems, "d4 manifest.json");
      const sets = manifest === null ? null : asRecord(manifest["sets"]);
      const b1 = sets === null ? null : asRecord(sets["b1-import"]);
      const oversize = b1 === null ? [] : (asArray(b1["generatedOversize"]) ?? []);
      if (oversize.length === 0) {
        oversizeNote = "registered as empty in manifest.json — not executed";
      } else {
        let oversizeOk = 0;
        /* >20 MiB：读体/解析前 413 语义拒绝，零持久化。 */
        try {
          await harness.service.importMaterial(harness.treeId, {
            filename: "oversize-file-bytes.md",
            bytes: buildOversizeFileBytes(),
          });
          problems.push("oversize file-bytes probe: >20 MiB import was NOT rejected (material-too-large expected)");
        } catch (error) {
          if (error instanceof MaterialTooLargeError) {
            oversizeOk += 1;
            lines.push("oversize >20MiB: rejected before parsing (material-too-large), zero persistence");
          } else {
            problems.push(`oversize file-bytes probe: unexpected error ${error instanceof Error ? error.message : String(error)}`);
          }
        }
        /* >200 页：页树装载后、内容解释前拒绝。 */
        const pagesImport = await harness.service.importMaterial(harness.treeId, {
          filename: "oversize-pages.pdf",
          bytes: buildOversizePagesPdf(201),
        });
        const pagesVersion = await untilTerminal(harness, pagesImport.material.id, 60_000, problems);
        if (pagesVersion !== null) {
          const parseError = pagesVersion.parseError ?? "";
          if (pagesVersion.parseStatus === "failed" && parseError.startsWith("pages-exceeded:")) {
            oversizeOk += 1;
            lines.push("oversize >200 pages: rejected before extracting (pages-exceeded), no text persisted");
          } else {
            problems.push(
              `oversize pages probe: got '${pagesVersion.parseStatus}' / '${parseError}' (expected failed pages-exceeded)`,
            );
          }
        }
        /* >1M UTF-16 单元：解析后、落库前拒绝。 */
        const unitsImport = await harness.service.importMaterial(harness.treeId, {
          filename: "oversize-text-units.md",
          bytes: buildOversizeTextUnitsBytes(),
        });
        const unitsVersion = await untilTerminal(harness, unitsImport.material.id, 60_000, problems);
        if (unitsVersion !== null) {
          const parseError = unitsVersion.parseError ?? "";
          if (unitsVersion.parseStatus === "failed" && parseError.startsWith("text-units-exceeded:")) {
            oversizeOk += 1;
            lines.push("oversize >1M units: rejected before persistence (text-units-exceeded), oversized text not stored");
          } else {
            problems.push(
              `oversize text-units probe: got '${unitsVersion.parseStatus}' / '${parseError}' (expected failed text-units-exceeded)`,
            );
          }
        }
        oversizeNote = `${String(oversizeOk)}/3 probes rejected correctly (${String(oversize.length)} registered)`;
      }
    }

    const passed = problems.length === 0 && readyOk === readyTotal && negativesOk === negativesTotal;
    const detail =
      `${String(readyOk)}/${String(readyTotal)} ready fixtures round-trip byte-exact ` +
      `(${registries.map((r) => `${r.registry.kind} ${String(r.registry.fixtures.length)}`).join(" + ")}); ` +
      `${String(negativesOk)}/${String(negativesTotal)} negatives rejected with the frozen reason ` +
      `(${[...negativeReasons.entries()].map(([r, n]) => `${r}x${String(n)}`).join(", ") || "none"}); ` +
      `same-bytes reuse ${String(reuseOk)}/${String(readyTotal)}; ` +
      `version pairs ${String(pairsExecuted)} executed / ${String(pairsRegistered)} registered; ` +
      `oversize probes: ${oversizeNote}`;
    return {
      status: passed ? "PASS" : "FAIL",
      exitCode: passed ? 0 : 2,
      detail,
      lines,
      problems,
    };
  } finally {
    harness.dispose();
  }
}

export { runB1ImportCheck };
